spring:
  application:
    name: calendarize
  datasource:
    username: sa
    password: Adteamkingp3
    url: jdbc:sqlserver://DESKTOP-0O190JQ\\SQLEXPRESS:1433;databaseName=calendarize;encrypt=true;trustServerCertificate=true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    show-sql: true
    hibernate:
      ddl-auto: none
server:
  port: 8080
